### ISSUE TITLE
HTML export only available for signed-in users

### ISSUE THREAD

**Issue by almereyda** [ishubin/schemio#610]
Given the current limitations in authentication and storage #607, access to HTML exports of an interactive scheme is only available to Google Drive users.

> As an anonymous, offline schemeio user, I would also like to export my interactive diagram to HTML, in order to being able to present it to third parties easily.

To commence the conversation about HTML export for offline users, I would like to ask, if there are any practical reasons, why offline cannot create HTML exports?

**Comment by ivanshubin-tomtom** [comment]
Is this about a self hosted FS based read only version of Schemio? Because Google drive backend is client based, so it is only exposed to you. As an offline user all you can do is use offline editor https://schemio.app/#/offline-editor/?m=edit and that's pretty much it. You can't access any documents from other Google drive users.

You can however host your own FS-based Schemio distribution and it has a view only mode https://github.com/ishubin/schemio/blob/master/README.md#configuration. Is this the one your issue is about?

**Comment by ishubin** [comment]
Is this issue about self hosted FS-based version of Schemio with view only mode https://github.com/ishubin/schemio/blob/master/README.md#configuration ?

Because as an offline user of schemio.app you can only access offline editor and you are not able to see documents of other Google drive users.

**Comment by almereyda** [comment]
Yes, somehow like that. This means as an offline Schemio user, I would have to download the JSON and deploy a view-only instance, to create an interactive, publicly viewable copy of it?

Else, I like the idea of an HTML export, but don't understand yet why it is not available when not being signed in. The ZIP wouldn't change despite one JSON file for the scheme, am I correct?

I like the idea of separating between live instances, a view-only Schemio.app and a separate Schemio player, which I wouldn't want to miss. Here I am merely wondering, why - technically or functionally - it isn't possible to have it available for anonymous users, too.

**Comment by ishubin** [comment]
ok, I see what you mean. I checked the offline-editor and indeed there is no way to export it as HTML. It does not make any sense. Will fix it

**Comment by almereyda** [comment]
Ah, cool! I didn't know this was unexpected at all, and considered the possibility of a technical limitation here. Good that is not the case.

**Comment by ishubin** [comment]
I have released a fix, it should be working now.
