### ISSUE TITLE
HTML player only available through static export

### ISSUE THREAD

**Issue by almereyda** [ishubin/schemio#611]
In a world in which Schemio understands to load Schemes from arbitrary URLs, we can also imagine a Schemio player, that is capable to do the same. Then distribution of the player can be decoupled from the scheme JSON. Thirdly this could provide us with an option, to distribute read-only copies of our schemes to third parties, via sharing a link to the player that points at a world-readable JSON file.

**Comment by ishubin** [comment]
I don't think I fully understand this feature request. Could you please elaborate a bit more on it? I have already implemented #609 that lets you export your document into a link. If you share that link with someone, they would be able to open the document that you have created in an offline editor. You can also choose to send plain scheme JSON to anyone and they can import it into offline editor at https://schemio.app/#/offline-editor?m=edit. I don't fully understand the use case of decoupling standalone HTML player from scheme JSON. The reason I implemented original exporting as HTML the way it is now, is so that users aren't bothered by scemio.app at all and can add their documents with Schemio player to their own websites and host it the way they want to. Or do you mean that we could use schemio.app for hosting standalone player and instead of exporting zip with the player we just generate a javascript code that you can add to your website?

**Comment by almereyda** [comment]
Thanks for considering this idea. Indeed it may have been presented a little loose.

If an independent standalone player implemented offline reading, e.g. by loading Scheme JSON files via CORS https://github.com/ishubin/schemio/issues/609#issuecomment-1210506710, it could offer the path to versioned links to static schemes, which cannot be edited. For example: A user decides to manually store Scheme JSON in a git repository that is synced to GitHub/-Lab/-ea, they could use the raw links for each file for every commit.

In the current implementation of the Schemio Offline Editor loading a Scheme from a URL fragment, we cannot separate distribution of interactive schemes from a Schemio deployment, and the user will always be able to press *Edit*. Also the Offline Editor offers more functionality than is needed to only show a Scheme to somebody else.

With a separate static player, that could possibly load remote files, we gain a completely independent environment for displaying interactive Schemes *that cannot be edited*

**Comment by ishubin** [comment]
What you describe to me looks a lot like static exporter that is already implemented in FS based distribution of Schemio (the one that you can run with Docker https://github.com/ishubin/schemio#running-with-docker).

If you send `POST` request to `/v1/static-export/start` route - it will export all your diagrams and media files into a folder, will generate an `index.html` file and put all Schemio resources there as well. You can take that exported folder and host it anywhere and it will show you the same stuff only without editing support. This feature is not yet documented as I totally forgot about it :)

**Comment by almereyda** [comment]
Here we are ;) Let me try this, and feed my experiences back later.

Is this static export returning a ZIP of that folder?
Or will that be stored on the file system of the container, and can be taken from there?
Then a CLI command would appear more suitable, to not involve a context switch (HTTP API vs. Container host terminal) when using this feature.

Yes, little documentation about #577 may help others, like me, in the future. Thank you for your kind responses.

**Comment by ishubin** [comment]
Yes, I haven't yet made up my mind how to expose this feature. Since FS based distribution is actually a web server, an API call is the first thing that came to mind. I don't really want to build a command for this, as maintaining it will make it more complicated (I had enough of all those complaints for different OS in my previous open-source project :) )

What I was thinking originally - is to come up with some simple UI that would show you the progress and give a visual confirmation of the exporting process.

I just wanted to have this static exporting functionality ready, so that I could in parallel also work on a demo project of Schemio. That's the reason it is not even documented yet, since I haven't yet built a proper UI for it, just only the minimal working code.

**Comment by almereyda** [comment]
Anyway, it's beautiful ;) I haven't seen anything that comes close to it in
its simplicity, yet completeness for the task.

**Comment by ishubin** [comment]
@almereyda If you don't mind, I will use this issue to finalise static exporter for FS based version of Schemio. Is that ok with you?

**Comment by ishubin** [comment]
I implemented and already released a UI for exporting all your diagrams to static distribution. It works only in FS based version. In the header there is now an "Admin" link which gives you a dropdown when hovered. For now it only has one option "Export all diagrams", but maybe in future there will be more. It then opens a modal and you can start the static exporter and, once finished, get a link to download a zip archive of all your diagrams. In the archive there is already an index.html file with all schemio assets. You can host this anywhere and it will let you view and browse all diagrams and folders. It still offers editing but you obviously cannot save, since there is no backend. Instead it will generate a patch, which you can later apply to original diagram. I am not sure if that's what you would want, but I envisioned that in future if I would want to share all my diagrams in this way, I would like to give the users an ability to modify them using patches.

<img width="1509" alt="Screenshot 2022-08-14 at 20 59 15" src="https://user-images.githubusercontent.com/949577/184551135-6f9abaa7-f468-421a-b14c-2a1230c702d4.png">

<img width="631" alt="Screenshot 2022-08-14 at 20 59 31" src="https://user-images.githubusercontent.com/949577/184551138-83e67a95-3d32-4305-b142-eb175be04b57.png">

**Comment by almereyda** [comment]
Very well! Happy to see this progressing wherever you deem fit. I will need to create a deployment and test it from there. From what I read this export bundles the schemes with the offline-editor set to view mode, am I right? I believe my original quest was to get the static player exposed for presentation purposes, where you couldn't accidentally change anything. But I like how you consider this primarily an interactive environment, from which accidental changes (user intent) could actually be kept.

And I'm very happy to consider changes as patches, since that works well with what I'm known to from Federated Wiki, or ActivityPub. In Federated Wiki we even also keep accidental patches, and save them to localStorage, when no authenticated remote is available.

**Comment by ishubin** [comment]
I am actually thinking to change the default settings and instead allow only view mode in exported static diagrams. But, I will keep it parameterized in the index.html file, so that if anyone really wants to they can allow editing.
