### ISSUE TITLE
Cannot open linked diagrams on localhost

### ISSUE THREAD

**Issue by LoveIsGrief** [ishubin/schemio#646]
**Main diagram**
![image](https://user-images.githubusercontent.com/2829538/197343315-cc081df7-5693-4312-8393-b0609df54749.png)

**target diagram**
![image](https://user-images.githubusercontent.com/2829538/197343372-4c606690-efeb-44a6-bd32-52f44e293db0.png)

**Result**

Clicking on the component doesn't work.

![image](https://user-images.githubusercontent.com/2829538/197343343-19c05bf9-f1cd-459d-a476-dffd245006ca.png)

# Stack

```
TypeError: e.scheme is undefined
    onComponentLoadRequested http://localhost:4010/assets/schemio.app.js:2
    promise callback*onComponentLoadRequested http://localhost:4010/assets/schemio.app.js:2
    ze http://localhost:4010/assets/schemio.app.js:2
    $emit http://localhost:4010/assets/schemio.app.js:2
    $emit http://localhost:4010/assets/schemio.app.js:2
    emitComponentLoadRequested http://localhost:4010/assets/schemio.app.js:2
    onLoadSchemeClick http://localhost:4010/assets/schemio.app.js:2
    ze http://localhost:4010/assets/schemio.app.js:2
    n http://localhost:4010/assets/schemio.app.js:2
    _wrapper http://localhost:4010/assets/schemio.app.js:2
    Gi http://localhost:4010/assets/schemio.app.js:2
    st http://localhost:4010/assets/schemio.app.js:2
    Ki http://localhost:4010/assets/schemio.app.js:2
    v http://localhost:4010/assets/schemio.app.js:2
    u http://localhost:4010/assets/schemio.app.js:2
    f http://localhost:4010/assets/schemio.app.js:2
    u http://localhost:4010/assets/schemio.app.js:2
    f http://localhost:4010/assets/schemio.app.js:2
    u http://localhost:4010/assets/schemio.app.js:2
    Rr http://localhost:4010/assets/schemio.app.js:2
    _update http://localhost:4010/assets/schemio.app.js:2
    i http://localhost:4010/assets/schemio.app.js:2
    get http://localhost:4010/assets/schemio.app.js:2
    un http://localhost:4010/assets/schemio.app.js:2
    exports http://localhost:4010/assets/schemio.app.js:2
    $mount http://localhost:4010/assets/schemio.app.js:2
    $mount http://localhost:4010/assets/schemio.app.js:2
    init http://localhost:4010/assets/schemio.app.js:2
    u http://localhost:4010/assets/schemio.app.js:2
    u http://localhost:4010/assets/schemio.app.js:2
    A http://localhost:4010/assets/schemio.app.js:2
    A http://localhost:4010/assets/schemio.app.js:2
    A http://localhost:4010/assets/schemio.app.js:2
    A http://localhost:4010/assets/schemio.app.js:2
    Rr http://localhost:4010/assets/schemio.app.js:2
    _update http://localhost:4010/assets/schemio.app.js:2
    i http://localhost:4010/assets/schemio.app.js:2
    get http://localhost:4010/assets/schemio.app.js:2
    run http://localhost:4010/assets/schemio.app.js:2
    cn http://localhost:4010/assets/schemio.app.js:2
``

# Environment`

Firefox 105.0.1 (64-bit)

**Comment by ishubin** [comment]
I think you are using it wrong, but I still see a bug in how it handles an error and links. Looks like links are completely broken on the component. But this is I guess also the confusing part. Links are just used for displaying links on the item, when it is clicked. I tested it on component and this behaviour is actually broken on it.

But, if you want your component to load another diagram, you need to specify it in the `Scheme ID` property of the component. Here it is:
<img width="1279" alt="Screenshot 2022-10-22 at 16 25 06" src="https://user-images.githubusercontent.com/949577/197344687-59d399c5-1d9c-41ab-805a-b732536e92e8.png">

In any case, this issue is still relevant because:
- Regular links are not working on components, I will fix that
- Error message is obscure, will fix it.
- The functionality is confusing. But I don't yet know a solution to make it easier

Thanks for reporting! This is so helpful, as it was difficult to test it all by myself

**Comment by ishubin** [comment]
Released a fix for regular events handling for components. It appeared that it did not handle "click", "mouse in" and "mouse out" events at all. I also changed the error message to a more meaningful
